### ISSUE TITLE
referencedGrokFields does not detect all referenced fields

### ISSUE THREAD

**Issue by boriseveoh** [fstab/grok_exporter#10]
When a grok field is referenced in the following way:
```
{{if eq .field "value"}}text{{end}}
```
The field is not detected by `referencedGrokFields` (in metrics.go).

Example config:
```
global:
    config_version: 2
input:
    type: file
    path: ./input
    readall: true
grok:
    patterns_dir: ./patterns
metrics:
    - type: gauge
      name: example
      help: not empty
      match: '%{NOTSPACE:val1} %{NOTSPACE:val2}'
      value: '{{.val1}}'
      labels:
          my_label: '{{if eq .val2 "test"}}yes{{else}}no{{end}}'
```
With input file:
```
1 test
2 nomatch
```
This results in the following error:
```
WARNING: Skipping log line: unexpected error while evaluating my_label template: template: my_label:1:5: executing "my_label" at <eq .val2 "test">: error calling eq: invalid type for comparison
```

If we change the definition of `my_label` to:
```
my_label: '{{.val2}} {{if eq .val2 "test"}}yes{{else}}no{{end}}'
```
The metric works as expected:
```
# HELP example not empty
# TYPE example gauge
example{my_label="nomatch no"} 2
example{my_label="test yes"} 1
```
