### ISSUE TITLE
Feature request: filter log records based on JSON fields

### ISSUE THREAD

**Issue by JensErat** [fstab/grok_exporter#101]
If I get it right, grok_exporter currently only makes use of JSON fields apart from the log messsage (from webhook tailer) for assigning labels. I'd like to propose a change to also filter based of JSON fields.

An example configuration, but I'm also fine with other approaches if anybody comes up with a better proposal:

```yaml
metrics:
# example log record: { "metadata": {"app": "foo"}, "stage": "prod", "log": "bad error event: 42!" }
- type: counter
  name: myapp_errors_total
  help: Total number of errors for my app
  match: 'bad error event'
  filters:
  - path: '.metadata.app' # jsonpath
    value: 'foo' # maybe even regex support?
  labels:
    stage: '{{ index .extra "stage" }}'
```

Before evaluating the grok matcher, grok_exporter would loop over all filters and have only pass those records that match all lines.

Why do I want this?

- make sure we only match the correct logs, not unrelated logs from another component (I might not even have control over the output)
- performance improvements, I guess matching some fields is much better performance compared to potentially complex grok patterns

Given there is agreement on this design proposal and we actually go the grok_exporter route (not decided yet, and might take some time), we would also contribute code.
