### ISSUE TITLE
Endpoint hostname

### ISSUE THREAD

**Issue by nezlis** [fstab/grok_exporter#119]
Hey there, hope you are doing well.

Could you please add endpoint hostname as built  in metric please?

It will be very helpful for guys without public DNS infrastructure to build human readable Grafana dashboard for grok exporter.

Thank you for your work, Fabian.

**Comment by fstab** [comment]
What do you think is more helpful, the `host` as configured in the [server section](https://github.com/fstab/grok_exporter/blob/master/CONFIG.md#server-section) in the config, or the output of the `hostname -f` command, or something else?

**Comment by nezlis** [comment]
From sysadmin perspective i thin "hostname -f" wold me more helpful.

Also, not shore if i need to mention it here, but we have problems with CA authentication. So there is no actual authentication going on, just regular https with self sign certificate. 

Server section of config file looks like so:

```
server:
    protocol: https
    host: 1.1.1.1 # just example
    port: 9144
    path: /metrics
    cert: /etc/grok_exporter/grok_exporter-cert.pem
    key: /etc/grok_exporter/grok_exporter-key.pem
    ca_key: /etc/grok_exporter/ca.pem
    client_auth_type: RequireAndVerifyClientCert
```
That king of approach for client cert auth working as expected in node_exporter project i have.
MB i'm missing some important detail in the configuration, if so, please correct me.
If you need some help with testing jus hit me up on twitter @artrmoroz
