### ISSUE TITLE
Need some help getting the metrics I am looking for.

### ISSUE THREAD

**Issue by cyberlink1** [fstab/grok_exporter#126]
I am new to grok and am learning a lot (Thank you for the documentation and the exporter) 

Im trying to get metrics from a miner log file. The entries look like this

`
GPUs: 1: 11.831 MH/s (15) 2: 11.967 MH/s (20) 3: 12.003 MH/s (24) 4: 12.004 MH/s (20) 5: 12.378 MH/s (17) 6: 12.286 MH/s (19)
`

using an online Grok pattern checker, I worked out the pattern 

I put this in a pattern file and call it with %{PHOENIX_HASH}

`
GPUs: %{INT:gpuid}: %{BASE16FLOAT:hashrate} MH/s \(%{INT:accepted}\)( %{INT:gpuid}: %{BASE16FLOAT:hashrate} MH/s \(%{INT:accepted}\))?( %{INT:gp
uid}: %{BASE16FLOAT:hashrate} MH/s \(%{INT:accepted}\))?( %{INT:gpuid}: %{BASE16FLOAT:hashrate} MH/s \(%{INT:accepted}\))?( %{INT:gpuid}: %{BASE16FLOAT:hashr
ate} MH/s \(%{INT:accepted}\))?( %{INT:gpuid}: %{BASE16FLOAT:hashrate} MH/s \(%{INT:accepted}\))?
`

This works in the pattern checker and it shows me the arrays I would expect for each variable.

Im trying to get it to output the gpuid as a label with the accepted as the metric for each of the GPU's in this line.

Im using a metric entry of 

`
metrics:
- type: gauge
  name: accepted
  help: Total number of accepted shares per GPU
  match: '%{PHOENIX_HASH}'
  value: '{{.accepted}}' 
  cumulative: false
  labels:
    accepted: '{{.gpuid}}'
`
However, what I get for output is a single entry for gpud 1 and that is it. I need an output for the 6 entries in the line.

So What am I doing wrong? 

Thanks for any help you can give.

**Comment by fstab** [comment]
I'm afraid it is currently not possible to do this in a single metric. You have to give your grok fields different names, like `gpuid1`, `accepted1`, `gpuid2`, `accepted2`, etc:

```
PHOENIX_HASH GPUs: %{INT:gpuid1}: %{BASE16FLOAT:hashrate} MH/s \(%{INT:accepted1}\)( %{INT:gpuid2}: %{BASE16FLOAT:hashrate} MH/s \(%{INT:accepted2}\))?( %{INT:gpuid3}: %{BASE16FLOAT:hashrate} MH/s \(%{INT:accepted3}\))?( %{INT:gpuid4}: %{BASE16FLOAT:hashrate} MH/s \(%{INT:accepted4}\))?( %{INT:gpuid5}: %{BASE16FLOAT:hashrate} MH/s \(%{INT:accepted5}\))?( %{INT:gpuid6}: %{BASE16FLOAT:hashrate} MH/s \(%{INT:accepted6}\))?
```

Then you have to define independent metrics for each GPU

```
- type: gauge
  name: accepted_1
  help: Total number of accepted shares for the first GPU
  match: '%{PHOENIX_HASH}'
  value: '{{.accepted1}}'
  cumulative: false
  labels:
    accepted: '{{.gpuid1}}'
- type: gauge
  name: accepted_2
  help: Total number of accepted shares for the second GPU
  match: '%{PHOENIX_HASH}'
  value: '{{.accepted2}}'
  cumulative: false
  labels:
    accepted: '{{.gpuid2}}'
- type: gauge
  name: accepted_3
  help: Total number of accepted shares for the third GPU
  match: '%{PHOENIX_HASH}'
  value: '{{.accepted3}}'
  cumulative: false
  labels:
    accepted: '{{.gpuid3}}'
- type: gauge
  name: accepted_4
  help: Total number of accepted shares for the fourth GPU
  match: '%{PHOENIX_HASH}'
  value: '{{.accepted4}}'
  cumulative: false
  labels:
    accepted: '{{.gpuid4}}'
- type: gauge
  name: accepted_5
  help: Total number of accepted shares for the fifth GPU
  match: '%{PHOENIX_HASH}'
  value: '{{.accepted5}}'
  cumulative: false
  labels:
    accepted: '{{.gpuid5}}'
- type: gauge
  name: accepted_6
  help: Total number of accepted shares for the sixth GPU
  match: '%{PHOENIX_HASH}'
  value: '{{.accepted6}}'
  cumulative: false
  labels:
    accepted: '{{.gpuid6}}'
```
