### ISSUE TITLE
Passing a .gz file as log file to grok_exporter.

### ISSUE THREAD

**Issue by Yagyansh** [fstab/grok_exporter#133]
Hi. I am using grok_exporter version: 1.0.0.RC1. I am looking to parse my AWS ELB logs using grok_exporter. The access logs for ELB are written every 5 minutes and the file is in .gz format. 

Now, I am wondering if we can pass the .gz file itself? What I am trying to do is give the path of the whole directory where the .gz files are stored.

Config File.

```
global:
    config_version: 2
input:
    type: file
    path: /home/Service_Logs/elblogs/*
    readall: true 
    patterns_dir: /home/Exporters/grok_exporter/patterns
metrics:
    - type: counter
      name: pattern_count
      help: Count for every pattern received, along-with Response Code and Method.
      match: '%{ALB}'
      labels:
          protocol: '{{.request_type}}'
          method: '{{.type}}'
          request_processing_time: '{{.request_processing_time}}'
          path: '{{.request_url}}'
          elb_code: '{{.elb_status_code}}'
          target_code: '{{.target_status_code}}'
server:
    host: localhost
    port: 9144
```
File format:
abl1.log.gz
alb2.log.gz
alb3.log.gz
alb4.log.gz

Is it somehow possible to do this? If not, can you please suggest a way to achieve this?
