### ISSUE TITLE
Restricting a Metric to Specific Log Files

### ISSUE THREAD

**Issue by WiFeng** [fstab/grok_exporter#135]
I found it could not work as decribed  (Restricting a Metric to Specific Log Files)

**Comment by fstab** [comment]
Please post your config file here, then I'll have a look what's wrong.

**Comment by WiFeng** [comment]
```
[work@web1 grok]$ cat config.yml
global:
  config_version: 3

input:
  type: file
  paths:
    - /usr/local/nginx/logs/access.apiv2.log
    - /mnt/logs/service/handle-recommend-friends.online.log
    - /mnt/logs/service/handle-live-delay-data.qa.log
  readall: false

imports:
- type: grok_patterns
  dir: ./patterns

grok_patterns:
- 'EXIM_MESSAGE [a-zA-Z ]*'

metrics:
- type: counter
  name: groktest_http_access_counter
  help: Total number of http access
  match: '\[%{HTTPDATE:timestamp}\] \"%{WORD:request_method} %{URIPATH:request_path}%{URIPARAM:request_param}? %{NOTSPACE:protocol}\" %{NUMBER:status:int} (?:%{NUMBER:bytes_sent:int}|-) %{QS:referrer} %{QS:user_agent} %{QS:x_forwarded_for} %{URIHOST:request_host} %{NUMBER:request_time:float}'
  labels:
    status: '{{.status}}'
    request_host: '{{.request_host}}'
    request_path: '{{.request_path}}'
    logfile: '{{base .logfile}}'

- type: histogram
  name: groktest_http_access_histogram
  help: Total number of http access
  match: '\[%{HTTPDATE:timestamp}\] \"%{WORD:request_method} %{URIPATH:request_path}%{URIPARAM:request_param}? %{NOTSPACE:protocol}\" %{NUMBER:status:int} (?:%{NUMBER:bytes_sent:int}|-) %{QS:referrer} %{QS:user_agent} %{QS:x_forwarded_for} %{URIHOST:request_host} %{NUMBER:request_time:float}'
  value: '{{.request_time}}'
  labels:
    status: '{{.status}}'
    request_host: '{{.request_host}}'
    request_path: '{{.request_path}}'
    logfile: '{{base .logfile}}'

- type: summary
  name: groktest_http_access_summary
  help: Total number of http access
  match: '\[%{HTTPDATE:timestamp}\] \"%{WORD:request_method} %{URIPATH:request_path}%{URIPARAM:request_param}? %{NOTSPACE:protocol}\" %{NUMBER:status:int} (?:%{NUMBER:bytes_sent:int}|-) %{QS:referrer} %{QS:user_agent} %{QS:x_forwarded_for} %{URIHOST:request_host} %{NUMBER:request_time:float}'
  value: '{{.request_time}}'
  quantiles: {0.5: 0.05, 0.9: 0.01, 0.99: 0.001, 0.999: 0.0001}
  labels:
  #  status: '{{.status}}'
    request_host: '{{.request_host}}'
    request_path: '{{.request_path}}'
  #  logfile: '{{base .logfile}}'

- type: counter
  name: grok_job_rec_friend_process_counter
  help: Total number of recommend friend job
  match: '\[INFO\] process job'
  path: /mnt/logs/service/handle-recommend-friends.online.log

- type: counter
  name: grok_job_rec_friend_ignore_counter
  help: Total number of recommend friend job
  match: '\[INFO\] ignore job'
  path: /mnt/logs/service/handle-recommend-friends.online.log

- type: counter
  name: grok_job_rec_friend_insert_counter
  help: Total number of recommend friend job
  match: '\[INFO\] insert discover pool ok'
  path: /mnt/logs/service/handle-recommend-friends.online.log


- type: histogram
  name: grok_job_live_delay_histogram
  help: The histogram of the live delay
  match: '\[INFO\] live delay. \[%{WORD:env}\] room_id\:%{NOTSPACE:room_id}, uid\:%{NUMBER:uid}, delay\:%{NUMBER:delay}, version\:%{NOTSPACE:version}, platform\:%{NOTSPACE:platform}, network\:%{NOTSPACE:network}, report_time\:%{NUMBER:report_time}'
  value: '{{.delay}}'
  labels:
    env: '{{.env}}'
    room_id: '{{.room_id}}'
    version: '{{.version}}'
    platform: '{{.platform}}'
    network: '{{.network}}'

- type: summary
  name: grok_job_live_delay_summary
  help: The summary of the live delay
  match: '\[INFO\] live delay. \[%{WORD:env}\] room_id\:%{NOTSPACE:room_id}, uid\:%{NUMBER:uid}, delay\:%{NUMBER:delay}, version\:%{NOTSPACE:version}, platform\:%{NOTSPACE:platform}, network\:%{NOTSPACE:network}, report_time\:%{NUMBER:report_time}'
  value: '{{.delay}}'
  quantiles: {0.5: 0.05, 0.9: 0.01, 0.99: 0.001, 0.999: 0.0001}
  labels:
    env: '{{.env}}'



server:
  protocol: http
  port: 9144
```
