### ISSUE TITLE
messy code problem

### ISSUE THREAD

**Issue by yangly0815** [fstab/grok_exporter#136]
when i grok the same line, i get two results, one is correct but the others was failed and i got messy code.
nodetool_status{instance_ip="192.168.75.129",instance_rack="my_rack",instance_state="**^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@@^@^@^@^@^@**UN"} 0
nodetool_status{instance_ip="192.168.75.129",instance_rack="my_rack",instance_state="UN"} 1
nodetool_status{instance_ip="192.168.75.130",instance_rack="my_rack",instance_state="^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@UN"} 0
nodetool_status{instance_ip="192.168.75.130",_instance_rack="my_rack",instance_state="UN"} 1

**Comment by fstab** [comment]
Wow, this looks weird. Could you please comment the line and your config? I'll have a look.

**Comment by yangly0815** [comment]
the line that i want to grok is following, and i store them in a file and i will refresh the file every 5 seconds:
```bash
192.168.75.129 UN  192.168.75.129   4.41 GB    256          ?       ad1b06f3-43c4-4bec-89a8-cc7bdd8cfcc4  rack01
192.168.75.130 UN  192.168.75.130  4.46 GB    256          ?       78be6786-f3a4-4a2e-b1d8-5b1f44f6b86d  rack01
```

the config i use is like this:
```yaml
global:
  config_version: 3
input:
  type: file
  paths:
  - ./status
  readall: true # Read from the beginning of the file? False means we start at the end of the file and read only new lines.
imports:
- type: grok_patterns
  dir: ./patterns
metrics:
- type: gauge
  name: status
  help: The node status in cluster.
  match: '%{IP}\s*(?<state>(UN|DN|\?N))\s*%{IP:ip}\s*(%{NUMBER:load}|(?<load>(\?)))\s*%{DATA:unit}\s*%{NUMBER:token}\s*(?<owns>(\?))\s*%{UUID:hostid}\s*%{GREEDYDATA:rack}'
  path: ./status
  value: '{{if eq .state "UN"}}1{{else}}0{{end}}'
  labels:
    instance_ip: '{{.ip}}'
    instance_rack: '{{.rack}}'
    instance_state: '{{.state}}'
```
