### ISSUE TITLE
Does labels support pipeline exec

### ISSUE THREAD

**Issue by gilbert-hsu** [fstab/grok_exporter#138]
We want to normalize our logs with multiple gsub

eg. 

```
metrics:
  - match:  %{IPORHOST:clientip} %{HTTPDUSER:ident} %{USER:auth} \[%{HTTPDATE:timestamp}\] "(?:%{WORD:verb} %{NOTSPACE:request}(?: HTTP/%{NUMBER:httpversion})?|%{DATA:rawrequest})" %{NUMBER:response} (?:%{NUMBER:bytes}|-)
  - labels:
      request: '{{gsub .request pattern1 replace1}} | {{gsub .request pattern2 replace2}} | ...'
```
or

```
  - labels:
      request: 
        - '{{gsub .request pattern1 replace1}}'
        - '{{gsub .request pattern2 replace2}}'
        - ...

**Comment by fstab** [comment]
You mean like this?

config
```yaml
global:
  config_version: 3
input:
  type: file
  path: ./example/messages.log
  readall: true
imports:
- type: grok_patterns
  dir: ./logstash-patterns-core/patterns
metrics:
- type: counter
  name: messages_total
  help: example for issue 138
  match: '%{NOTSPACE:request}'
  labels:
    request: '{{gsub (gsub .request "a" "b") "c" "b"}}'
```
messages.log
```
abc
```
result
```
messages_total{request="bbb"} 1
```
