### ISSUE TITLE
Calculate a min/max/average value based on log data

### ISSUE THREAD

**Issue by mad-ady** [fstab/grok_exporter#157]
Hello,
I'm trying to use grok_exporter to parse an application log that looks something like this:
```
2021-06-15 09:24:19,243 - INFO - SomethingSomething device AAAAA; Processing time is:4511us
2021-06-15 09:24:19,260 - INFO - SomethingSomething device BBBBB; Processing time is:3928us
```
I can count the lines and use "device" as a label and get the number of occurrences per device.
What I'd like to do now is parse the processing time (per device) and do a calculation of min/max/average processing time based on the data in the log file. I know I can export the raw data, but that would be more difficult (and a lot of data). Something like exporting a "Min processing time" metric, a "Max processing time" and an "Average processing time". The min/max/averages period could be controlled by the `retention` parameter.

I'd like to ask if such processing is possible in some way (using jinja perhaps?) with the stock grok exporter?
Thank you!

**Comment by mad-ady** [comment]
I've solved this issue by using the histogram data type.
Now I can get distribution in "time buckets" for my requests.
Sample config for the metric:
```
  -   buckets:
        - 0.5
        - 1
        - 2.5
        - 5
        - 10
        - 20
        - 50
        - 100
        - 200
        - 400
        help: Widget processing time distribution
        labels:
            host: myhost
            logfile: '{{.logfile}}'
            device: '{{.device}}'
        match: device (?<device>[^\s]+); Processing time is:(?<processing_time>[0-9\.]+)us
        name: widget_processing_time
        type: histogram
        value: '{{.processing_time}}'
```
And then I followed this tutorial to display the values on a heat map in grafana: https://grafana.com/blog/2020/06/23/how-to-visualize-prometheus-histograms-in-grafana/
