### ISSUE TITLE
Values not updating.

### ISSUE THREAD

**Issue by pslobo** [fstab/grok_exporter#18]
Hi, I'm trying to get grok_exporter to parse a log file created by a node.js app and then send that data to Prometheus. I'm most probably "holding it wrong" because the matched values aren't update when new lines are written to the log file. When I restart the grok_exporter, then it sends the last read match to Prometheus and doesn't update with new values.

Example of log lines:

```
2017-09-14 14:52 +00:00: The proxy currently has 9 miners connected at 5638 h/s with an average diff of 18800
```

I've got something along these lines in the config file (so far):

```yaml
global:
    config_version: 2
input:
    type: stdin
grok:
    patterns_dir: ./patterns
metrics:
    - type: gauge
      name: proxy_miners_count
      help: Number of miners connected to proxy.
      match: '%{TIMESTAMP_ISO8601:date} %{ISO8601_TIMEZONE}: The proxy currently has %{NUMBER:miners:int} miners connected at %{NUMBER:hash:int} h/s with an average diff of %{NUMBER:diff:int}'
      value: '{{.miners}}'

    - type: gauge
      name: proxy_hash_count
      help: Total H/s of miners connected to proxy.
      match: '%{TIMESTAMP_ISO8601:date} %{ISO8601_TIMEZONE}: The proxy currently has %{NUMBER:miners:int} miners connected at %{NUMBER:hash:int} h/s with an average diff of %{NUMBER:diff:int}'
      value: '{{.hash}}'
```

Is it an error on my part or is this something not intended for grok_exporter? The log file gets update every 1-2 seconds so I'd expect to see this data reflected on Prometheus.

Cheers and thanks for any help
Pedro
