### ISSUE TITLE
mutiple depth doc support

### ISSUE THREAD

**Issue by novvoo** [fstab/grok_exporter#184]
example:
` " /opt/data/docker/containers/*/*.log"` or `/opt/data/docker/containers/abc/abc.log support`
config:
```
apiVersion: v1
data:
  config.yml: |-
    global:
      config_version: 3
    input:
      type: file
      paths: 
      - /opt/data/docker/containers/*/*.log
      readall: false
      fail_on_missing_logfile: false
    imports:
    - type: grok_patterns
      dir: patterns
    grok_patterns:
      - 'CUSTOMSTR (?:\d|\p{L}|-|_)+'
      - 'ERROR ERROR'
      - 'SERVICE \[%{CUSTOMSTR:service}'
      - 'REASON Fail：%{GREEDYDATA}'
      - 'EBAYACCOUNT ID \[%{CUSTOMSTR:ebayID}\]'
    metrics:
      - type: counter
        name: logcounter_total
        help: Total CUSTOMSTR of Package count.
        match: '%{TIMESTAMP_ISO8601:timestamp}%{GREEDYDATA:data1}IP \[%{IP:ip}\]%{GREEDYDATA:data2}%{ERROR:error}%{GREEDYDATA:data3}%{SERVICE}%{GREEDYDATA:data4}%{EBAYACCOUNT:ebayaccount}%{GREEDYDATA:data5}%{REASON:reason}'
        labels:
          IP: '{{.ip}}'
          level: '{{.error}}'
          service: '{{.service}}'
          ebayID: '{{.ebayID}}'
          reason: '{{.reason}}'
    server:
      port: 9100
kind: ConfigMap
metadata:
  name: grok-exporter-daemonset-config
  namespace: monitoring

```
k8s:
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  generation: 10
  labels:
    app: grok-exporter
    release: grok-exporter
  name: grok-exporter
  namespace: monitoring
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: grok-exporter
      release: grok-exporter
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: grok-exporter
        release: grok-exporter
      name: grok-exporter
    spec:
      affinity: {}
      containers:
      - env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: pwxvin/grok-exporter:v1.0.0-RC4
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - |
              #!/usr/bin/env bash -e
              wget --spider -T 5 -q -t 2 127.0.0.1:9100/metrics | echo $?
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: grok-exporter
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - |
              #!/usr/bin/env bash -e
              /grok/grok_exporter -showconfig -config /grok/config.yml
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "2"
            memory: 800Mi
          requests:
            cpu: 100m
            memory: 200Mi
        securityContext:
          privileged: false
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /grok/config.yml
          name: grok-exporter-config
          readOnly: true
          subPath: config.yml
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
          readOnly: true
        - mountPath: /var/log
          name: varlog
          readOnly: true
        - mountPath: /var/run/docker.sock
          name: varrundockersock
          readOnly: true
        - mountPath: /opt/data/docker/containers/
          name: extras
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: monitoring-updater
      serviceAccountName: monitoring-updater
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 384
          name: grok-exporter-daemonset-config
        name: grok-exporter-config
      - hostPath:
          path: /var/lib/docker/containers
          type: ""
        name: varlibdockercontainers
      - hostPath:
          path: /var/log
          type: ""
        name: varlog
      - hostPath:
          path: /var/run/docker.sock
          type: ""
        name: varrundockersock
      - hostPath:
          path: /opt/data/docker/containers/
          type: ""
        name: extras
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
```

**Comment by novvoo** [comment]
use /var/log/containers/*.log
```
        volumeMounts:
        - mountPath: /grok/config.yml
          name: grok-exporter-config
          readOnly: true
          subPath: config.yml
        - mountPath: /var/log/containers/
          name: varlogcontainers
          readOnly: true
        - mountPath: /var/log/pods
          name: varlogpods
          readOnly: true
        - mountPath: /var/run/containerd/containerd.sock
          name: varruncontainerdcontainerdsock
          readOnly: true
        - mountPath: /var/lib/docker/containers/
          name: varlibdockercontainers
          readOnly: true
        - mountPath: /var/run/docker.sock
          name: varrundockersock
          readOnly: true
        - mountPath: /opt/data/docker/containers/
          name: extras
          readOnly: true
      dnsPolicy: ClusterFirst
```
