### ISSUE TITLE
Logrotate

### ISSUE THREAD

**Issue by roidelapluie** [fstab/grok_exporter#19]
Hi,

Cam we have inotify support, so that when a file is rotated we pick up the new one? thanks

**Comment by fstab** [comment]
`grok_exporter` uses `inotify` already, so this should work (except you configure `poll_interval_seconds`, which explicitly disables `inotify`).

**Comment by roidelapluie** [comment]
Strangely enough this working in my test but not the real prod logs

![x4](https://user-images.githubusercontent.com/291750/31588474-5a942b1c-b1f2-11e7-9d8d-e8f358b50d66.png)

**Comment by roidelapluie** [comment]
PS: on the graph above I restart grok_exporter at 4:30

**Comment by fstab** [comment]
So logrotate runs around 01:20, then `grok_exporter` doesn't get any new log lines until you restart it? This is strange, it should work. Is there any way to reproduce the error (like a test setup with the same OS and same filesystem)?

**Comment by roidelapluie** [comment]
I have that accross all the servers -- 5 servers. All RHEL6.

Running logotate -f works...

**Comment by roidelapluie** [comment]
I tried to reproduce it on a vagrant box but that did not work.

**Comment by roidelapluie** [comment]
Also, I have that every day. it is consistent.

not sur how I can get logs??

Also I see that the fd (/proc/xx/fd) is not open for the new file.

**Comment by roidelapluie** [comment]
So ..  works when I test it but not in prod. Maybe in prod the file is not created as fast as it should be? any idea?

**Comment by fstab** [comment]
It should not depend on how fast the logfile is created. After the logfile is moved, `grok_exporter` waits for an inotify `IN_CREATE` event, and then opens the file again. Maybe there is a reason that the event is not triggered? Are you using another filesystem in prod than in your tests, or a network fileystem on prod but a local filesystem on test?

**Comment by roidelapluie** [comment]
Filesystems are ext4.

logrotate file:
```
/var/log/httpd/*log {
    rotate 30
    daily
    missingok
    dateext
    compress
    notifempty
    sharedscripts
    delaycompress
    postrotate
        /sbin/service httpd reload > /dev/null 2>/dev/null || true
    endscript                                                                                                                                                                                        
}

```

**Comment by roidelapluie** [comment]
grok_exporter config:

```
global:
    config_version: 2
input:
    type: file
    path: /var/log/httpd/prd_request_ws_log
    readall: false
grok:
    patterns_dir: /var/lib/prometheus/grok_exporter
    additional_patterns:
    - 'APACHE_MESSAGE none'
metrics:
    - type: histogram
      name: nippin_http_requests_duration_microseconds
      help: Number of http requests
      buckets: [1000000, 3000000, 5000000]
      value: '{{.response_microsecond}}'
      match: '%{SYSLOG5424SD} %{IP} %{NOTSPACE} %{NOTSPACE} %{QS} %{QS} %{NUMBER:status} %{NUMBER:size} %{NUMBER:response_microsecond}'
      labels:
        environment: 'prod'
        status: '{{.status}}'
server:
    host: 172.21.10.6
    port: 9144
```
