### ISSUE TITLE
Grok - fields with ( ) in them. 

### ISSUE THREAD

**Issue by VR6Pete** [fstab/grok_exporter#38]
Hey,

Here is my Grok query but for some reason it cannot find a match when I have the brackets in the Referrer and user agent name.

%{TIMESTAMP_ISO8601:logtime} %{WORD:s-sitename} %{WORD:s-computername} %{IPORHOST:s-ip} %{WORD:cs-method} %{NOTSPACE:cs-uri-stem} %{NOTSPACE:cs-uri-query} %{NUMBER:s-port} %{NOTSPACE:cs-username} %{IPORHOST:c-ip} %{NOTSPACE:cs-version} %{NOTSPACE:cs(User-Agent)} %{NOTSPACE:cs(Referer)} %{IPORHOST:cs-host} %{NUMBER:sc-status} %{NUMBER:sc-substatus} %{NUMBER:c-win32-status} %{NUMBER:sc-bytes} %{NUMBER:cs-bytes} %{NUMBER:time-taken}

Example log item:

2018-02-02 00:01:32 W3SVC1 UKAPPSVR 172.18.131.173 GET /123/I/Home/PLMonstants - 80 Joe+Bloggs 172.18.17.185 HTTP/1.1 Mozilla/5.0+(Windows+NT+6.1;+Trident/7.0;+rv:11.0)+like+Gecko https://blahblah.co.uk/theappname/live/app/thingy localhost 200 0 0 3393 2644 90

was using http://grokconstructor.appspot.com/do/match to validate?

Any ideas what I could be doing wrong or if there is something I can change with the query string to work around the bracket issue.

Unfortunately I cannot change the name of the field as we push into splunk as well. 

Thanks.

Pete

**Comment by fstab** [comment]
In grok_exporter, you need to distinguish two names:
* The names used in the grok pattern (like the name `cs_user_agent` in `%{NOTSPACE:cs_user_agent}`) are just used inside the `grok_exporter` config file, to configure which field ends up in which label. These names are never exposed to Prometheus.
* The label names (like `my_own_label` in the example below) are presented to Prometheus.

In most cases the same name is used for the grok pattern matches and the Prometheus label names, but it is perfectly ok to use different names like this:
```yaml
global:
    config_version: 2
input:
    type: file
    path: ./example/test.log
    readall: true # Read from the beginning of the file? False means we start at the end of the file and read only new lines.
grok:
    patterns_dir: ./logstash-patterns-core/patterns
metrics:
    - type: counter
      name: test_metric_total
      help: Total number of matched lines
      match: '%{TIMESTAMP_ISO8601:logtime} %{WORD:s_sitename} %{WORD:s_computername} %{IPORHOST:s_ip} %{WORD:cs_method} %{NOTSPACE:cs_uri_stem} %{NOTSPACE:cs_uri_query} %{NUMBER:s_port} %{NOTSPACE:cs_username} %{IPORHOST:c_ip} %{NOTSPACE:cs_version} %{NOTSPACE:cs_user_agent} %{NOTSPACE:cs_referer} %{IPORHOST:cs_host} %{NUMBER:sc_status} %{NUMBER:sc_substatus} %{NUMBER:c_win32_status} %{NUMBER:sc_bytes} %{NUMBER:cs_bytes} %{NUMBER:time_taken}'
      labels:
          my_own_label: '{{.cs_user_agent}}'
server:
    host: localhost
    port: 9144
```
Only the label name `my_own_label` is presented to Prometheus, the grok pattern name `cs_user_agent` is only used inside the `grok_exporter` config file.

There should be no need to use special characters for grok pattern names (like `cs_user_agent`). If you want to use special characters in the Prometheus label name: This is unfortunately impossible, because Prometheus label names must match this regular expression `^[a-zA-Z_][a-zA-Z0-9_]*$` (see [here](https://github.com/prometheus/common/blob/master/model/labels.go#L86)).

For the label value there are of course no restrictions.
