### ISSUE TITLE
grok_exporter v 0.2.6 resident memory rising

### ISSUE THREAD

**Issue by raokrutarth** [fstab/grok_exporter#55]
I have a fairly frequently updated log file that I am using grok exporter to count specific log entries. I see that the resident memory usage by the exporter is quite high and growing. This happens 3/4 of the time in my env. 

Graph:
![image](https://user-images.githubusercontent.com/8570223/54384549-b8e7b900-4651-11e9-95fb-1ced62a0829f.png)

The config is:
```
global:
  config_version: 2
grok:
  additional_patterns:
  - BASE10NUM (?<![0-9.+-])(?>[+-]?(?:(?:[0-9]+(?:\.[0-9]+)?)|(?:\.[0-9]+)))
  - DATA .*?
  - NUMBER (?:%{BASE10NUM})
  - DAEMON [a-zA-Z_\-]+
  - NAELOGLEVEL LOG_[\S+]
  - MESSAGE [\S\s\S]?*
  - YEAR (?>\d\d){1,2}
  - HOUR (?:2[0123]|[01]?[0-9])
  - MINUTE (?:[0-5][0-9])
  - SECOND (?:(?:[0-5]?[0-9]|60)(?:[:.,][0-9]+)?)
  - TIME (?!<[0-9])%{HOUR}:%{MINUTE}(?::%{SECOND})(?![0-9])
  - MONTHNUM (?:0?[1-9]|1[0-2])
  - MONTHDAY (?:(?:0[1-9])|(?:[12][0-9])|(?:3[01])|[1-9])
  - ISO8601_TIMEZONE (?:Z|[+-]%{HOUR}(?::?%{MINUTE}))
  - TIMESTAMP_ISO8601 %{YEAR}-%{MONTHNUM}-%{MONTHDAY}[T ]%{HOUR}:?%{MINUTE}(?::?%{SECOND})?%{ISO8601_TIMEZONE}?
  - LEVEL (LOG_)?([Aa]lert|ALERT|[Tt]race|TRACE|[Dd]ebug|DEBUG|DBG|[Nn]otice|NOTICE|[Ii]nfo|INFO|[Ww]arn?(?:ing)?|WARN?(?:ING)?|[Ee]rr|ERR?(?:OR)?|[Cc](rit)+(?:ical)?|CRIT?(?:ICAL)?|[Ff]atal|FATAL|[Ss]evere|SEVERE|EMERG(?:ENCY)?|[Ee]merg(?:ency)?)
input:
  path: /var/log/messages
  poll_interval_seconds: 5
  type: file
metrics:
- help: all log entries seperated by daemon
  labels:
    daemon: '{{.daemon}}'
  match: '%{TIMESTAMP_ISO8601:time} %{DAEMON:daemon}.*%{LEVEL:level}.*'
  name: benchmark_all_daemon_log_entry_counts
  type: counter
- help: count of panic entries in the log by go daemons
  labels:
    daemon: '{{.daemon}}'
  match: '%{TIMESTAMP_ISO8601:time} %{DAEMON:daemon}.*panic.*'
  name: benchmark_go_daemon_log_panic_counts
  type: counter

[other confidential counters]
```

**Comment by fstab** [comment]
This is a bug. Will investigate where this comes from. Thanks for reporting.

**Comment by fstab** [comment]
Found a memory leak in `gsub`. Pushed a fix and will make a bugfix release soon. Thanks for reporting!
Are you actually using `gsub` (in your `[other confidential counters]` config) or is there another memory leak I am not aware of?

**Comment by raokrutarth** [comment]
I'm using summary and gauge metrics. Do those call `gsub` in any way?

**Comment by fstab** [comment]
I released a bugfix release 0.2.7. Could you check if this solves the issue?

**Comment by raokrutarth** [comment]
I used the 0.2.7 release binary in my env but I am still seeing the leak. Currently, a bash script restarts the exporter every 1.5 hrs.

![image](https://user-images.githubusercontent.com/8570223/55901359-0cc8bd80-5b7e-11e9-9e97-8ba1475d44ff.png)

**Comment by fstab** [comment]
There's a buffer in `grok_exporter` that where new log lines are stored before they are passed on through the matcher. The load of this buffer can be monitored with the `grok_exporter_line_buffer_peak_load` metric. Could you monitor this and check if this is constantly growing?

**Comment by raokrutarth** [comment]
![image](https://user-images.githubusercontent.com/8570223/56237995-3b450d80-6042-11e9-9994-c153f8b76b3f.png)

![image](https://user-images.githubusercontent.com/8570223/56238021-4c8e1a00-6042-11e9-8086-45cb13182324.png)

**Comment by raokrutarth** [comment]
I also noticed a different trend over a longer run (~2.5 days), the peaks are not as large later on.

![image](https://user-images.githubusercontent.com/8570223/56238153-9ecf3b00-6042-11e9-85ec-d63ebe02f34a.png)

**Comment by fstab** [comment]
Thanks for the data. If I see the colors correctly the `grok_exporter_line_buffer_peak_load` is constantly increasing. That means log lines are written faster than `grok_exporter` processes them. The buffer with unprocessed log lines keeps growing, and `grok_exporter` eventually runs out of memory.

One thing you could do is to figure out why processing takes so long. Sometimes there is a single regular expression taking most of the processing time. The metric `grok_exporter_lines_processing_time_microseconds_total` gives you the total processing time in microseconds per metric. With a Prometheus query like `rate(grok_exporter_lines_processing_time_microseconds_total[5m])` you can evaluate that in the time window of the last 5 minutes.

Could you run that query to see if there is any metric that takes significantly longer than the others? Maybe we can optimize the regular expression for that metric to make processing faster.

**Comment by raokrutarth** [comment]
![image](https://user-images.githubusercontent.com/8570223/56243112-a98fcd00-604e-11e9-9377-5e87b4c0cf15.png)

I can take `all_daemon_log_entry_counts` but `benchmark_ovsdb_logs` are needed.


The metric is 
`- help: ovsdb-server log entries
  labels:
    level: '{{.level}}'
  match: '%{TIMESTAMP_ISO8601:time} ovsdb-server(\[%{NUMBER}\])?: .*%{LEVEL:level}'
  name: benchmark_ovsdb_logs
  type: counter`

**Comment by fstab** [comment]
It doesn't look too bad. Some things you can try:
* as far as I can see you only use `level` as a label, so you could replace `%{TIMESTAMP_ISO8601:time}` with `%{TIMESTAMP_ISO8601}` or even leave it out entirely.
* `(\[%{NUMBER}\])?: ` is optional and you don't use it, so you could remove it
* It might be faster to replace `.*` with `.*?` depending on if the level is more at the end of the line or the beginning of the line.

**Comment by raokrutarth** [comment]
An optional flag like `--max-rss=1G` for the exporter could help. Once the cap is reached, it drops older items for new ones. Just a suggestion.

**Comment by fstab** [comment]
I didn't add a buffer limit so far because dropping log lines makes `grok_exporter` unreliable, you might miss fatal log messages.

On the other hand, if you have to restart `grok_exporter` you also might miss messages. So an optional flag is probably the lesser evil. I will look into it.

Meanwhile I added a log message, so if log messages are written faster than they are processed `grok_exporter` will print a warning to the console.

**Comment by raokrutarth** [comment]
Thanks for taking a look. I am not really parsing the log messages from `grok_exporter` because my env can't take any actions regardless of what it says. Also noticed the memory spikes are progressing faster. Unable to verify if there have been changes in the number of log messages but I though the data might be useful.

![image](https://user-images.githubusercontent.com/8570223/56437334-c9fc9900-6293-11e9-96d5-fb297ddd15ed.png)

**Comment by fstab** [comment]
I started implementing a limit for the number of lines in the line buffer. Specifying a number of lines is not as convenient as specifying a max amount of memory, but it's easier to implement and better than running out of memory. I will comment here when it's done.

**Comment by fstab** [comment]
I implemented a config option for the `input` section in the configuration file:

```yaml
input:
    type: file
    path: /var/log/messages
    max_lines_in_buffer: 100000
```

The example would drop the buffer if it reaches 100000 log lines. This is not good, because you loose 100000 log lines in monitoring, but it's better than to run out of memory and crash.

You need to build `grok_exporter` from source code to get this feature. It will be part of the next release.
