### ISSUE TITLE
Replace Function in Matched Captures

### ISSUE THREAD

**Issue by varundmishra** [fstab/grok_exporter#56]
Hi,
Firstly Thank you for the wonderful work with this, It works really well.
I just wanted to check if there is a way wherein subtext within a capture group can be replaced with something??

For example, I have a lot of URL's being captured like:
/abc/def/ghi/number/123123/jkl/mno
/abc/def/ghi/number/123124/jkl/mno
/abc/def/ghi/number/987654/jkl/mno
/abc/def/ghi/number/654763/jkl/mno

Currently I do not need the digits in the URL, it is creating a lot of unique metrics because of this, is there a way where in post capturing, the URL can be replaced to something like this:
/abc/def/ghi/number/x/jkl/mno

This would also mean instead of 5 separate metrics with count 1, I would have 1 metric with count 5.

Thanks,
Varunn

**Comment by fstab** [comment]
Hi, sorry for the late reply. Yes, this is possible with the `gsub` function. Example:

Logfile:
```
INFO: request to path /abc/def/ghi/number/123123/jkl/mno
INFO: request to path /abc/def/ghi/number/123124/jkl/mno
INFO: request to path /abc/def/ghi/number/987654/jkl/mno
INFO: request to path /abc/def/ghi/number/654763/jkl/mno
```

config
```
global:
    config_version: 2
input:
    type: file
    path: ./logfile.log
    readall: true
grok:
    patterns_dir: ../logstash-patterns-core/patterns
metrics:
    - type: counter
      name: requests_total
      help: Total number of requests, partitioned by path.
      match: '.* %{URIPATH:path}'
      labels:
          path: '{{gsub .path "(.*)/[0-9]*/(.*)" "\\1/{id}/\\2" }}'
host: localhost
port: 9144
```

explanation:

`gsub input pattern replacement` searches for the `pattern` in `input` and replaces it with `replacement`. In the example, it searches for `"(.*)/[0-9]*/(.*)"` which is a pattern with two capture groups: `(.*)` is the first capture group, capturing everything befor the id, and `(.*)` is the second capture group, capturing everything after the id. The replacement `"\\1/{id}/\\2"` references the first capture group `\\1` and the second capture group `\\2` but the id is replaced with the fixed string `{id}`.

result
```
requests_total{path="/abc/def/ghi/number/{id}/jkl/mno"} 4
```

See gsub in [CONFIG.md](https://github.com/fstab/grok_exporter/blob/master/CONFIG.md).
