### ISSUE TITLE
grok_exporter couldn't keep up with the load

### ISSUE THREAD

**Issue by twang11** [fstab/grok_exporter#64]
We are running grok_exporter in a docker container. The logstash collects and writes to the logfile that grok_exporter is picking up. Also logstash writes to another file that Splunk is picking up.

Splunk reports higher and we believe the correct number of transaction counts, however, grok_exporter seems like not able to keep up, only reports about 1/3 of the TPS. grok_exporter seems to catch up only at the early morning low traffic hours.

There is no out of memory and high CPU issue. 

We have 1 counter, 2 gauges, 3 histograms, each with 11 labels.  In the /metrics endpoint, it produces about 70k different time series.

How do you recommend to go about debugging this issue?

Build Info:

`branch="master",builddate="2018-05-31",goversion="go1.10.2",platform="linux-amd64",revision="62d82f8",version="0.2.5"`

Config Info:

```
global:
    config_version: 2
input:
    type: file
    path: /usr/share/logstash/output/log/apg_stats.log
    fail_on_missing_logfile: false
    readall: false
    poll_interval_seconds: 5
```
