### ISSUE TITLE
How to use log line timestamp as sample timestamp

### ISSUE THREAD

**Issue by muzammil360** [fstab/grok_exporter#71]
Hi. It seems that by default the timestamp associated with the sample is the one at which log file is scrapped (which by default is 15s). This seems to be inadequate if you want to measure time interval between two event (e.g. `event1_start` and `event1_end`). Is there any way we can associate the sample timestamp with `'%{DATE} %{TIME}'`?

**Comment by fstab** [comment]
Unfortunately this is currently not possible.

However, there is work in progress: `grok_exporter`'s templates support a `timestamp` function for converting a timestamp to a Unix timestamp (number of seconds since 1970).

Example log line:
```
2014-07-02 20:52:39 INFO this is some start event
```
Example config:
```
global:
    config_version: 2
input:
    type: file
    path: ./example/timestamp.log
    readall: true
grok:
    patterns_dir: ./logstash-patterns-core/patterns
    additional_patterns:
    - 'TIMESTAMP [0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}'
    - 'MESSAGE .*'
metrics:
    - type: counter
      name: test_counter
      help: test counter
      match: '%{TIMESTAMP:t} %{MESSAGE:m}'
      labels:
          orig_timestamp: '{{.t}}'
          unix_timestamp: '{{timestamp "2006-01-02 15:04:05" .t}}'
          message: '{{.m}}'
server:
    host: localhost
    port: 9144
```
Example output:
```
test_counter{message="INFO this is some start event",orig_timestamp="2014-07-02 20:52:39",unix_timestamp="1.404334359e+09"} 1
```
The missing functionality to achieve what you want would be:
* match two lines (the start event and the end event) for creating a single duration metric
* Subtract the start timestamp from the end timestamp (in Unix format) to calculate the metric value (for example, as a histogram metric).

I think it would be useful, but it's not implemented.

As the `timestamp` function alone is not very useful, I didn't even document it, but in case anyone's interested it works like golang's [time.Parse()](https://golang.org/pkg/time/#Parse).
