### ISSUE TITLE
Error - monitoring multiple log files

### ISSUE THREAD

**Issue by sacgmz** [fstab/grok_exporter#77]
Hello...!
This is my configuration 
```
global:
    config_version: 2

input:
    type: file
    paths: 
    -  /srv/grok_exporter/*.log
    -  /var/grok_exporter/*.log
    readall: false
    fail_on_missing_logfile: false
grok:
    patterns_dir: "/srv/grok_exporter/patterns"
    additional_patterns: ['FPMDATE %{MONTHDAY}/%{MONTH}/%{YEAR}:%{TIME} %{ISO8601_TIMEZONE}']

metrics:
    -   type: counter
        name: no_of_segfaults
        help: Example counter metric with labels.
        match: "%{SYSLOGPROG}: segfault at %{BASE16NUM} ip %{BASE16NUM} sp %{BASE16NUM} error %{NUMBER} in %{GREEDYDATA}"

server:
  host: <ip>
  port: xxxx
```
error:
```
"grok_exporter"[3746]: Failed to load /srv/grok_exporter/grok_exporter.yml: invalid input configuration: 'input.path' is required for input type "file"
```

The same configuration file works for a single log file but not for multiple files what might be the reason for this error?

**Comment by fstab** [comment]
I tried your config with the current grok_exporter 1.0.0.RC2 and it works. Could you copy-and-paste the following, just to make sure that there is no strange invisible character in the file?
```yaml
global:
  config_version: 2
input:
  type: file
  paths:
  - /srv/grok_exporter/*.log
  - /var/grok_exporter/*.log
  fail_on_missing_logfile: false
grok:
  patterns_dir: /srv/grok_exporter/patterns
  additional_patterns:
  - FPMDATE %{MONTHDAY}/%{MONTH}/%{YEAR}:%{TIME} %{ISO8601_TIMEZONE}
metrics:
- type: counter
  name: no_of_segfaults
  help: Example counter metric with labels.
  match: '%{SYSLOGPROG}: segfault at %{BASE16NUM} ip %{BASE16NUM} sp %{BASE16NUM}
    error %{NUMBER} in %{GREEDYDATA}'
server:
  protocol: http
  host: 0.0.0.0
  port: 9144
```
