### ISSUE TITLE
Multi log files monitor and lables config problems

### ISSUE THREAD

**Issue by xuanyuanaosheng** [fstab/grok_exporter#92]
Hi, 
 
We want to use grok_exporter to analysis multi files in `/app_log/[component name]/applogs/*.log`

The grok_exporter version: grok_exporter-1.0.0.RC3.linux-amd64.

The config is
```
global:
  config_version: 3
  retention_check_interval: 53s
input:
  type: file
  paths: 
  - /app_log/test_gm_acl_server/applogs/wal_acl_batch_wal_worker.log
  - /app_log/test_gm_internal/applogs/walse-api.log
  - /app_log/test_gm_lvcon_consumer/applogs/wal_gw_lvcon.log
  - /app_log/test_gm_router_batch/applogs/wal-gw-router.log
  - /app_log/test_gm_sender_adv/applogs/wal-gw-sender.log
  - /app_log/test_gm_sender_batch/applogs/wal-gw-sender.log
  - /app_log/test_gm_sender_check/applogs/walse-sender-checker.log
  readall: false 
  fail_on_missing_logfile: true 
  poll_interval: 5
imports:
- type: grok_patterns
  dir: /etc/grok_exporter/patterns
grok_patterns:
  - 'EXIM_MESSAGE [a-zA-Z ]*'
  - 'EXIM_SENDER_ADDRESS F=<%{EMAILADDRESS}>'
metrics:
- type: counter
  name: ERROR_LOG
  help: The number of message counts contain the spectfic strings.
  match: 'ERROR'
  labels:
    logfile: '{{.logfile}}'
    check_string: 'ERROR'

server:
  host: 0.0.0.0
  port: 9144
```

The output of the command `curl localhost:9144/metrics | grep grok_exporter` metrics is: 

```
# HELP grok_exporter_build_info A metric with a constant '1' value labeled by version, builddate, branch, revision, goversion, and platform on which grok_exporter was built.
# TYPE grok_exporter_build_info gauge
grok_exporter_build_info{branch="release",builddate="2020-02-14",goversion="go1.13.8",platform="linux-amd64",revision="6381c25",version="1.0.0.RC3"} 1
# HELP grok_exporter_line_buffer_load Number of lines that are read from the logfile and waiting to be processed.
# TYPE grok_exporter_line_buffer_load gauge
grok_exporter_line_buffer_load{interval="1m",value="max"} 8
grok_exporter_line_buffer_load{interval="1m",value="min"} 0
# HELP grok_exporter_line_processing_errors_total Number of errors for each metric. If this is > 0 there is an error in the configuration file. Check grok_exporter's console output.
# TYPE grok_exporter_line_processing_errors_total counter
grok_exporter_line_processing_errors_total{metric="ERROR_LOG"} 0
# HELP grok_exporter_lines_matching_total Number of lines matched for each metric. Note that one line can be matched by multiple metrics.
# TYPE grok_exporter_lines_matching_total counter
grok_exporter_lines_matching_total{metric="ERROR_LOG"} 7
# HELP grok_exporter_lines_processing_time_microseconds_total Processing time in microseconds for each metric. Divide by grok_exporter_lines_matching_total to get the averge processing time for one log line.
# TYPE grok_exporter_lines_processing_time_microseconds_total counter
grok_exporter_lines_processing_time_microseconds_total{metric="ERROR_LOG"} 404
# HELP grok_exporter_lines_total Total number of log lines processed by grok_exporter.
# TYPE grok_exporter_lines_total counter
grok_exporter_lines_total{status="ignored"} 31289
grok_exporter_lines_total{status="matched"} 7
```

The question:
-----------------------
1.  The config `input` section list the files to be monitor, but the output is not collect by file?
2.  The  ` labels:` section does not work?  Could you help to fix the config?
