### ISSUE TITLE
multiple match filters

### ISSUE THREAD

**Issue by VinistoisR** [fstab/grok_exporter#99]
I have log lines like this 

```
May  3 00:41:07 172.16.50.150 /var/log/pald.log[821] ﻿MALONE UPS 1: Output Current = 5.00
May  3 00:41:09 172.16.50.150 /var/log/pald.log[821] ﻿MALONE UPS 1: Output Current = 4.00
May  3 00:41:17 172.16.50.150 /var/log/pald.log[839] ﻿MALONE UPS 2: Battery Minutes Remaining = 32
May  3 00:41:24 172.16.50.150 /var/log/pald.log[821] ﻿MALONE UPS 1: Input Voltage = 120.1
May  3 00:41:25 172.16.50.150 /var/log/pald.log[839] ﻿MALONE UPS 2: Input Voltage = 119.0
May  3 00:41:27 172.16.50.150 /var/log/pald.log[821] ﻿MALONE UPS 1: Battery Voltage = 54.3
May  3 00:41:36 172.16.50.150 /var/log/pald.log[839] ﻿MALONE UPS 2: Battery Minutes Remaining = 33
```

so I matched them up with this filter
```
match: '%{MONTH:month}%{SPACE}%{MONTHDAY:day}%{SPACE}%{TIME:time}%{SPACE}%{USER}%{SPACE}%{PATH}%{NOTSPACE}%{NUMBER}%{NOTSPACE}%{SPACE}%{NOTSPACE:location}%{SPACE}%{NOTSPACE:asset}%{SPACE}%{INT:id}%{NOTSPACE}%{SPACE}(?<measurement>%{WORD}%{SPACE}%{WORD})%{SPACE}%{NOTSPACE}%{SPACE}%{NUMBER:val}'
```
This works great, except it fails to catch the message that has a third word in the value label.  So I made another one that catches it:
```
match: '%{MONTH:month}%{SPACE}%{MONTHDAY:day}%{SPACE}%{TIME:time}%{SPACE}%{USER}%{SPACE}%{PATH}%{NOTSPACE}%{NUMBER}%{NOTSPACE}%{SPACE}%{NOTSPACE:location}%{SPACE}%{NOTSPACE:asset}%{SPACE}%{INT:id}%{NOTSPACE}%{SPACE}(?<measurement>%{WORD}%{SPACE}%{WORD}%{SPACE}%{WORD})%{SPACE}%{NOTSPACE}%{SPACE}%{NUMBER:val}'
```
but I couldn't figure out how to run them both at the same time. 

So, I just doubled up on the docker containers instead, and that way I end up with my exact desired result:

![image](https://user-images.githubusercontent.com/36953653/80895725-d421e780-8c9c-11ea-8857-abf422d76eba.png)

But there must be a way to get both of those into the same line?

**Comment by fstab** [comment]
You are pretty close. A pattern to match an arbitrary number of words looks like this:
```
(%{WORD}%{SPACE}?)+
```
That means: A word, followed by an optional space, and the whole thing might repeat multiple times.

Instead of copying this directly into your match, you could define it as a pattern named `WORDS` and use it in your match like this:
```yaml
grok_patterns:
- 'WORDS (%{WORD}%{SPACE}?)+'
metrics:
- type: gauge
  name: gauge_1
  help: example gauge 1
  match: '%{MONTH:month}%{SPACE}%{MONTHDAY:day}%{SPACE}%{TIME:time}%{SPACE}%{USER}%{SPACE}%{PATH}%{NOTSPACE}%{NUMBER}%{NOTSPACE}%{SPACE}%{NOTSPACE:location}%{SPACE}%{NOTSPACE:asset}%{SPACE}%{INT:id}%{NOTSPACE}%{SPACE}%{WORDS:measurement}%{SPACE}%{NOTSPACE}%{SPACE}%{NUMBER:val}'
  labels:
    measurement: '{{.measurement}}'
  value: '{{.val}}'
```

However, your match is a bit long, and you might consider simplifying it. This depends on your loglines and it's hard to tell without knowing what else is in your log, but to give you an example: If you know the measurement starts after a `:`, and the separater between the measurement and the value is a ` = `, and you don't care about the rest, you could write the match like this:
```yaml
- type: gauge
  name: gauge_2
  help: example guage 2
  match: ': %{WORDS:measurement} = %{NUMBER:val}'
  labels:
    measurement: '{{.measurement}}'
  value: '{{.val}}'
```
